title: Chalmovský
description: "Writings from (and often to) Chalmovský"
url: "https://chalmovsky.com"
baseurl: ""

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
